# This workflow builds the previews for pull requests when a certain label is applied.
# The actual deployment happens as part of a dedicated second workflow to avoid security
# issues where the building would otherwise occur in an authorized context where secrets
# could be leaked. More details can be found here:

# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/.

name: Build docs for preview deployment

on:
  pull_request:
    types: [synchronize, labeled]

permissions: read-all

jobs:
  adev-build:
    runs-on: ubuntu-latest
    if: |
      (github.event.action == 'labeled' && github.event.label.name == 'docs: preview') ||
      (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'docs: preview'))
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@d4f17986de97f198b59da03bf1b5fc4c78497a40
      - name: Setup Bazel
        uses: angular/dev-infra/github-actions/bazel/setup@d4f17986de97f198b59da03bf1b5fc4c78497a40
      - name: Setup Bazel RBE
        uses: angular/dev-infra/github-actions/bazel/configure-remote@d4f17986de97f198b59da03bf1b5fc4c78497a40
      - name: Install node modules
        run: pnpm install --frozen-lockfile
      - name: Build docs site
        run: pnpm bazel build //docs:build.production
      - uses: angular/dev-infra/github-actions/previews/pack-and-upload-artifact@d4f17986de97f198b59da03bf1b5fc4c78497a40
        with:
          workflow-artifact-name: 'docs-preview'
          pull-number: '${{github.event.pull_request.number}}'
          artifact-build-revision: '${{github.event.pull_request.head.sha}}'
          deploy-directory: './dist/bin/docs/dist/browser'
