name: Scheduled CI

on:
  schedule:
    - cron: '0 0/4 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  browsers_snapshot_test:
    runs-on: ubuntu-latest-4core
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@fb30926790c6225d553b91a4818cab2fdde4fb4e
        with:
          cache-node-modules: true
      - name: Setup Bazel
        uses: angular/dev-infra/github-actions/bazel/setup@fb30926790c6225d553b91a4818cab2fdde4fb4e
      - name: Setup Bazel RBE
        uses: angular/dev-infra/github-actions/bazel/configure-remote@fb30926790c6225d553b91a4818cab2fdde4fb4e
      - name: Setting up Angular snapshot builds
        # Angular snapshots must be set up first so that the yarn install properly
        # updates the yarn.lock as expected with the changes
        run: node ./scripts/circleci/setup-angular-snapshots.js main
      - name: Install node modules
        run: yarn install
      - name: Run Browser tests
        run: yarn bazel test --build_tag_filters=-e2e --test_tag_filters=-e2e --build_tests_only -- src/...
      - uses: ./.github/actions/slack
        if: ${{ failure() && github.event_name == 'push' }}
        with:
          JOB_NAME: 'Browser snapshot test'
          SLACK_BOT_TOKEN: ${{ secrets.ANGULAR_ROBOT_SLACK_TOKEN }}

  linker_snapshot_tests:
    runs-on: ubuntu-latest-4core
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@fb30926790c6225d553b91a4818cab2fdde4fb4e
        with:
          cache-node-modules: true
      - name: Setup Bazel
        uses: angular/dev-infra/github-actions/bazel/setup@fb30926790c6225d553b91a4818cab2fdde4fb4e
      - name: Setup Bazel RBE
        uses: angular/dev-infra/github-actions/bazel/configure-remote@fb30926790c6225d553b91a4818cab2fdde4fb4e
      - name: Setting up Angular snapshot builds
        # Angular snapshots must be set up first so that the yarn install properly
        # updates the yarn.lock as expected with the changes
        run: node ./scripts/circleci/setup-angular-snapshots.js main
      - name: Install node modules
        run: yarn install
      - name: Run linker tests using AOT
        run: yarn test-linker-aot
      - name: Run linker tests using JIT
        run: yarn test-linker-jit
      - uses: ./.github/actions/slack
        if: ${{ failure() && github.event_name == 'push' }}
        with:
          JOB_NAME: 'Linker snapshot test'
          SLACK_BOT_TOKEN: ${{ secrets.ANGULAR_ROBOT_SLACK_TOKEN }}

  mdc_snapshot_test:
    runs-on: ubuntu-latest-4core
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@fb30926790c6225d553b91a4818cab2fdde4fb4e
        with:
          cache-node-modules: true
      - name: Setup Bazel
        uses: angular/dev-infra/github-actions/bazel/setup@fb30926790c6225d553b91a4818cab2fdde4fb4e
      - name: Setup Bazel RBE
        uses: angular/dev-infra/github-actions/bazel/configure-remote@fb30926790c6225d553b91a4818cab2fdde4fb4e
      - name: Setting up Angular snapshot builds
        # Angular snapshots must be set up first so that the yarn install properly
        # updates the yarn.lock as expected with the changes
        run: node ./scripts/circleci/setup-angular-snapshots.js main
      - name: Install MDC Canary
        run: node ./scripts/circleci/setup-mdc-canary.js
      - name: Install node modules
        run: yarn install
      - name: Run browser tests using MDC Canary
        run: bazel test --build_tag_filters=-docs-package,-e2e --test_tag_filters=-e2e --build_tests_only -- src/...
      - uses: ./.github/actions/slack
        if: ${{ failure() && github.event_name == 'push' }}
        with:
          JOB_NAME: 'MDC Snapshot test'
          SLACK_BOT_TOKEN: ${{ secrets.ANGULAR_ROBOT_SLACK_TOKEN }}

  monitor-docs-site:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@fb30926790c6225d553b91a4818cab2fdde4fb4e
        with:
          cache-node-modules: true
      - name: Install node modules
        run: yarn install --frozen-lockfile
      - name: Check Docs Site
        run: yarn ci-docs-monitor-test
      - uses: ./.github/actions/slack
        if: ${{ failure() && github.event_name == 'push' }}
        with:
          JOB_NAME: 'Docs site monitoring'
          SLACK_BOT_TOKEN: ${{ secrets.ANGULAR_ROBOT_SLACK_TOKEN }}
