name: Scheduled CI

on:
  schedule:
    - cron: '0 0/4 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  browsers_snapshot_test:
    runs-on: ubuntu-latest-4core
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@3baae85f9070f71460c61d13adea605f2f584678
        with:
          cache-node-modules: true
      - name: Setup Bazel
        uses: angular/dev-infra/github-actions/bazel/setup@3baae85f9070f71460c61d13adea605f2f584678
      - name: Setup Bazel RBE
        uses: angular/dev-infra/github-actions/bazel/configure-remote@3baae85f9070f71460c61d13adea605f2f584678
        with:
          google_credential: ${{ secrets.RBE_TRUSTED_BUILDS_USER }}
      - name: Setting up Angular snapshot builds
        # Angular snapshots must be set up first so that the pnpm install properly
        # updates the lock file as expected with the changes
        run: node ./scripts/circleci/setup-angular-snapshots.js main
      - name: Install node modules
        run: pnpm install
      - name: Run Browser tests
        run: pnpm bazel test --build_tag_filters=-e2e --test_tag_filters=-e2e --build_tests_only -- src/...
      - uses: ./.github/actions/slack
        if: ${{ failure() && github.event_name == 'push' }}
        with:
          JOB_NAME: 'Browser snapshot test'
          SLACK_BOT_TOKEN: ${{ secrets.ANGULAR_ROBOT_SLACK_TOKEN }}

  linker_snapshot_tests:
    runs-on: ubuntu-latest-4core
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@3baae85f9070f71460c61d13adea605f2f584678
        with:
          cache-node-modules: true
      - name: Setup Bazel
        uses: angular/dev-infra/github-actions/bazel/setup@3baae85f9070f71460c61d13adea605f2f584678
      - name: Setup Bazel RBE
        uses: angular/dev-infra/github-actions/bazel/configure-remote@3baae85f9070f71460c61d13adea605f2f584678
        with:
          google_credential: ${{ secrets.RBE_TRUSTED_BUILDS_USER }}
      - name: Setting up Angular snapshot builds
        # Angular snapshots must be set up first so that the pnpm install properly
        # updates the lock files as expected with the changes
        run: node ./scripts/circleci/setup-angular-snapshots.js main
      - name: Install node modules
        run: pnpm install
      - name: Run linker tests using AOT
        run: pnpm test-linker-aot
      - name: Run linker tests using JIT
        run: pnpm test-linker-jit
      - uses: ./.github/actions/slack
        if: ${{ failure() && github.event_name == 'push' }}
        with:
          JOB_NAME: 'Linker snapshot test'
          SLACK_BOT_TOKEN: ${{ secrets.ANGULAR_ROBOT_SLACK_TOKEN }}

  monitor-docs-site:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@3baae85f9070f71460c61d13adea605f2f584678
        with:
          cache-node-modules: true
      # See: https://github.com/puppeteer/puppeteer/pull/13196 and
      # https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md.
      - name: Disable AppArmor
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
      - name: Install node modules
        run: pnpm install --frozen-lockfile
      - name: Check Docs Site
        run: ppnpm ci-docs-monitor-test
      - uses: ./.github/actions/slack
        if: ${{ failure() && github.event_name == 'push' }}
        with:
          JOB_NAME: 'Docs site monitoring'
          SLACK_BOT_TOKEN: ${{ secrets.ANGULAR_ROBOT_SLACK_TOKEN }}
